// ---- End-to-end encryption for "encrypted sessions" ----
//
// A symmetric AES-256-GCM key is generated by the session creator and shared with
// guests in the share-link URL *fragment* (see invite/branded), which browsers
// never send to the relay. The relay therefore routes opaque ciphertext blobs and
// can never read session content — see docs/superpowers/specs/2026-06-16-encrypted-sessions-design.md.
//
// GCM gives confidentiality *and* tamper-evidence: a relay cannot forge or alter a
// blob without the key. The message `type` is passed as additional authenticated
// data (AAD) so a relay can't replay a ciphertext as a different message type.

const IV_BYTES = 12; // 96-bit nonce, the standard/required size for AES-GCM
const KEY_BYTES = 32; // AES-256

function toBase64Url(bytes: Uint8Array): string {
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]!);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function fromBase64Url(s: string): Uint8Array {
  const b64 = s.replace(/-/g, "+").replace(/_/g, "/");
  const padded = b64.length % 4 === 0 ? b64 : b64 + "=".repeat(4 - (b64.length % 4));
  const bin = atob(padded);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

// Hand WebCrypto a plain ArrayBuffer-backed copy. The DOM/Workers `BufferSource`
// type rejects `Uint8Array<ArrayBufferLike>` (it could be a SharedArrayBuffer); a
// bounded slice is always a real ArrayBuffer and sidesteps that variance.
function ab(u: Uint8Array): ArrayBuffer {
  return u.buffer.slice(u.byteOffset, u.byteOffset + u.byteLength) as ArrayBuffer;
}

/** Generate a fresh, exportable AES-256-GCM session key (the creator serialises it into the link). */
export async function generateKey(): Promise<CryptoKey> {
  // Exportable so the creator can serialise it into the share link's fragment.
  return crypto.subtle.generateKey({ name: "AES-GCM", length: 256 }, true, ["encrypt", "decrypt"]);
}

/** Serialise a key to an unpadded base64url string (43 chars for 32 bytes). */
export async function exportKeyB64(key: CryptoKey): Promise<string> {
  const raw = new Uint8Array(await crypto.subtle.exportKey("raw", key));
  return toBase64Url(raw);
}

/**
 * Import a key from base64url (or standard-alphabet, padded) text. Guests import
 * the key non-extractably — they only ever need to encrypt/decrypt, never re-export.
 */
export async function importKeyB64(b64: string): Promise<CryptoKey> {
  const raw = fromBase64Url(b64);
  if (raw.length !== KEY_BYTES) throw new Error("e2ee: invalid key length");
  return crypto.subtle.importKey("raw", ab(raw), { name: "AES-GCM" }, false, ["encrypt", "decrypt"]);
}

/**
 * Encrypt a JSON-serialisable payload, returning `base64url(iv ‖ ciphertext+tag)`.
 * `aad` (the message type) is authenticated but not encrypted.
 */
export async function seal(payload: unknown, key: CryptoKey, aad: string): Promise<string> {
  const iv = crypto.getRandomValues(new Uint8Array(IV_BYTES));
  const plaintext = new TextEncoder().encode(JSON.stringify(payload));
  const additionalData = new TextEncoder().encode(aad);
  const ct = new Uint8Array(
    await crypto.subtle.encrypt({ name: "AES-GCM", iv: ab(iv), additionalData: ab(additionalData) }, key, ab(plaintext)),
  );
  const out = new Uint8Array(iv.length + ct.length);
  out.set(iv, 0);
  out.set(ct, iv.length);
  return toBase64Url(out);
}

/**
 * Decrypt an envelope produced by {@link seal}. Throws if the key is wrong, the
 * AAD does not match, or the ciphertext was tampered with (GCM auth failure).
 */
export async function open(envelope: string, key: CryptoKey, aad: string): Promise<unknown> {
  const bytes = fromBase64Url(envelope);
  if (bytes.length <= IV_BYTES) throw new Error("e2ee: envelope too short");
  const iv = bytes.subarray(0, IV_BYTES);
  const ct = bytes.subarray(IV_BYTES);
  const additionalData = new TextEncoder().encode(aad);
  const plaintext = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: ab(iv), additionalData: ab(additionalData) },
    key,
    ab(ct),
  );
  return JSON.parse(new TextDecoder().decode(plaintext));
}
